# Generated by GitHub Copilot on 2025-11-03 00:00
from __future__ import annotations

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="best_before_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Number of days the produce stays at peak quality.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="certifications",
            field=models.CharField(
                blank=True,
                help_text="Organic, FPO or other certification names.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="farming_practice",
            field=models.CharField(
                choices=[
                    ("organic", "Organic"),
                    ("natural", "Natural"),
                    ("conventional", "Conventional"),
                    ("hydroponic", "Hydroponic"),
                ],
                default="conventional",
                help_text="Primary growing method used.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="harvest_date",
            field=models.DateField(blank=True, help_text="Optional harvest date for traceability.", null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="quality_grade",
            field=models.CharField(
                choices=[
                    ("premium", "Premium grade"),
                    ("standard", "Standard grade"),
                    ("economy", "Economy grade"),
                ],
                default="standard",
                help_text="Visible quality grade to reassure buyers.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="storage_instructions",
            field=models.TextField(blank=True, help_text="Tips customers should follow after delivery."),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("l", "Litre"),
                    ("piece", "Piece"),
                    ("bunch", "Bunch"),
                ],
                default="kg",
                help_text="Measurement customers will see when ordering.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Amount of produce included per unit.",
                max_digits=6,
                validators=[MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
